export const labelMap = {
  firstname: 'First name',
  secondname: 'Second name',
  gender: 'Gender',
  birthdate: 'Birthdate',
  placeofbirth: 'Place of birth',
  nationality: 'Nationality',
  nationalid: 'National ID',
  nationaldoctype: 'National doctype',
  nationaldocid: 'National doc ID',
  nationaldocissuedate: 'National doc issue date',
  nationaldocexpirydate: 'National doc expiry date',
  telephone: 'Telephone',
  twitter: 'Twitter',
  facebook: 'Facebook',
  instagram: 'Instagram',
  youtube: 'Youtube',
  wechat: 'Wechat',
  tiktok: 'Tiktok',
  linkedin: 'Linkedin',
  vk: 'Vk',
  github: 'Github',
  telegram: 'Telegram',
  qq: 'Qq',
  snapchat: 'Snapchat',
  reddit: 'Reddit',
};
